name: multispecies-resistance
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - openblas
  - pytorch
  - rasterio
  - matplotlib
  - jupyterlab
  - contextily
  - geopandas
  - geodatasets
  - folium
  - pykrige
  - networkx
  - trimesh
  - dggrid
  - mkdocs
  - mkdocs-material
